<?php

	//application details
		$apps[$x]['name'] = 'Call Recordings';
		$apps[$x]['uuid'] = '56165644-598d-4ed8-be01-d960bcb8ffed';
		$apps[$x]['category'] = '';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '1.1';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = 'http://www.fusionpbx.com';
		$apps[$x]['description']['en-us'] = 'Call Recordings';
		$apps[$x]['description']['en-gb'] = 'Call Recordings';
		$apps[$x]['description']['nl-nl'] = 'Gespreksopnamen';

	//permission details
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_add';
		//$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_edit';
		//$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_all';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_play';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_download';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_transcribe';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y = 0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "95cb740e-e377-4852-8894-06441c61e78b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "filesystem_retention_days";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "90";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Number of days to retain the maintenance logs in the database.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e329db05-2967-422a-a71f-d0175b083828";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "record_extension";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "mp3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recording file format options: wav, mp3";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f8dada74-82a0-4175-8268-2333de308d9d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "record_name";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "\${year}\${month_number}\${day}.\${time}.\${caller_id_number}.\${uuid}.mp3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recording download template. Options: \${uuid}, \${caller_id_name}, \${caller_id_number}, \${caller_destination}, \${destination_number}, \${date}, \${call_direction}, \${year}, \${month_name}, \${month_number}, \${day}, \${time}";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b7a3c2f5-9d0e-4baf-b231-11e251601b62';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'call_recordings';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'transcription_enabled';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'boolean';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = 'false';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Enable or disable automatic transcription of call recordings.';

		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'd75eeb38-c214-4201-8f45-514c13ef2892';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'call_recordings';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'email';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'text';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Optional default email address for sending call recording transcriptions.';

		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = '4f998d0b-1d66-499e-b418-8f5139b6b12d';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'call_recordings';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_transcription_time';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '2700';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Max recording length in seconds that will be transcribed.';

		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = '76d099ea-24b4-4720-bbb8-1962f3085947';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'call_recordings';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'min_transcription_time';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '60';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Min recording length in seconds that will be transcribed.';
